name: Call Eclipse Dash License Scanner (Go)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  release:
    types: [published]

permissions:
  contents: read
  actions: write

jobs:
  call-remote-dash-workflow:
    secrets: inherit
    uses: eclipse-xfsc/dev-ops/.github/workflows/eclipse-dash-licence-node.yml@main
